[build]
  base = "Frontend/angular-app"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/angular-app/browser"

[[redirects]]
  from = "/api/*"
  to = "https://diplomarbeit-bestellapp.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200